### ISSUE TITLE
Transform numpy array to CenteredGrid

### ISSUE THREAD

**Issue by HDFengChina** [tum-pbs/PhiFlow#130]
Hi,

I hope to use PhiFlow as the env in my model. Thus, I need to calculate the next field with given the certain velocities and pressure. 

I can transform the calculated field to array by values.native(), but I met a challenge when I want to transform the given field (array) to CenteredGrid or StaggeredGrid.

Is there any method can transform the numpy array to CeteredGrid in PhiFlow ?

Thank you.

**Comment by holl-** [comment]
Hi, yes you can construct a `CenteredGrid` from a `math.Tensor` which you can with `wrap` or `tensor`.
```python
v_array = np.empty([64, 64, 2])
v_tensor = wrap(v_array, spatial('x,y'), channel('vector'))
grid = CenteredGrid(v_tensor, extrapolation.PERIODIC, bounds=Box(x=(0, 1), y=(0, 1)))
```
For constructing staggered grids, see [here](https://tum-pbs.github.io/PhiFlow/Cookbook.html).
