### ISSUE TITLE
Code of Writing Fluid Simulations in ΦFlow doesn't work

### ISSUE THREAD

**Issue by whw-alex** [tum-pbs/PhiFlow#143]
Can you please provide the complete code of https://tum-pbs.github.io/PhiFlow/Fluid_Simulation.html? I tried to run the first code block but got `ValueError: could not convert string to float: 'periodic'`. Thanks!

**Comment by holl-** [comment]
Right, you need to run
```bash 
!pip install phiflow
```
before the first cell. I'll add it to the notebook

**Comment by whw-alex** [comment]
I installed phiflow but still got that error.

**Comment by holl-** [comment]
If you run this in a clean notebook, it should work. Which version are you running? You can check with
`phi.verify()`.

**Comment by whw-alex** [comment]
I run it in a clean notebook and the first error is now gone. But I can't run the code `plot(field.curl(velocity_trj), animate='time', same_scale=False)` in my notebook. The error is `CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1200x500', '-pix_fmt', 'rgba', '-framerate', '10.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', '/tmp/tmpjs46q90w/temp.m4v']' returned non-zero exit status 1.` But I have installed ffmpeg 4.3 in my virtual environment. I wonder if you know how to solve this problem. Thanks!

**Comment by holl-** [comment]
Sorry, this is a matplotlib / ffmpeg problem and I'm not familiar enough with these libraries to see the issue. You could try saving a matplotlib video from their demos.
