### ISSUE TITLE
what differential equation does the velocity satisfy

### ISSUE THREAD

**Issue by whw-alex** [tum-pbs/PhiFlow#144]
Hi! I have trouble understanding what differential equation the velocity in https://tum-pbs.github.io/PhiFlow/Fluid_Simulation.html satisfies. And why is that?

**Comment by holl-** [comment]
Hey, the velocity evolves according to the Navier-Stokes equations consisting of the advection and diffusion terms (u⋅∇)u−ν∇²u (equation under "Operator Splitting").
The incompressibility constraint ∇ · u = 0 is implemented via the pressure-term ∇p. The gravity term g is not simulated here.

If you have further questions, let me know!

**Comment by whw-alex** [comment]
Thanks for your answer! I wonder if you can tell me the relationship between 0.1 in `v = diffuse.explicit(v, 0.1, dt)` and the variable ν. Highly appreciate your work!

**Comment by holl-** [comment]
The 0.1 is the diffusivity / viscosity. It is exactly ν in the equation. It's inversely proportional to the Reynolds number.

**Comment by whw-alex** [comment]
Thank you so much!
