### ISSUE TITLE
Failing to replicate Wake_Flow example

### ISSUE THREAD

**Issue by crackalamoo** [tum-pbs/PhiFlow#170]
Hello,

I am attempting to replicate the [Wake_Flow example](https://tum-pbs.github.io/PhiFlow/examples/grids/Wake_Flow.html). I have copied the code exactly, and I get the error:

```
extrapolations = tuple(sorted(extrapolations, key=lambda e: e.pad_rank))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

When I remove the `@jit_compile` decoration, the simulation runs. But I do not get the turbulent pattern behind the cylinder as shown in the example. This is what I get instead:

![cylinder_curl](https://github.com/user-attachments/assets/7c4a6a72-7876-4ab0-91eb-53edcc54cb01)

What could be going on here? For reference, here is my exact code:

```python
from phi.jax.flow import *
import matplotlib.animation as animation
import matplotlib.pyplot as plt
from tqdm import tqdm

cylinder = geom.infinite_cylinder(x=20, y=50, radius=10, inf_dim='z')
plot({"Top view": cylinder['x,y'], "Side view": cylinder['x,z']})
plt.show()

pbar = tqdm(total=200)

@jit_compile
def step(v, p, dt=1.):
    v = advect.semi_lagrangian(v, v, dt)
    v, p = fluid.make_incompressible(v, cylinder, Solve(x0=p))
    pbar.update(1)
    return v, p

boundary = {'x-': vec(x=2, y=0, z=0), 'x+': ZERO_GRADIENT, 'y': PERIODIC, 'z': PERIODIC}
v0 = StaggeredGrid((8., 0, 0), boundary, x=128, y=64, z=8, bounds=Box(x=200, y=100, z=5))
v_trj, p_trj = iterate(step, batch(time=200), v0, None)

v_trj_2d = v_trj[{'z': 4, 'vector': 'x,y'}]
anim = plot(v_trj_2d.time[100:].curl(), animate='time')
anim.save('cylinder_curl.gif')
plt.show()

plot(v_trj_2d.time[-1], cylinder['x,y'], overlay='args')
plt.show()
```

**Comment by holl-** [comment]
Hi, the turbulence only develops after some time. You'll have to run the simulation for longer unfortunately.

As for the jit error, could you run `pip install --upgrade phiml` and try again?

**Comment by crackalamoo** [comment]
Thank you! When I run the simulation for longer (400 timesteps) I see the expected turbulence. I'm curious though, I'm running for the same number of steps and the same `dt` as the example. Shouldn't I see turbulence at the same time?

Also, I ran `pip install --upgrade phiml` and this got rid of the error, but now the code is extremely slow (~3 hours estimated time, while without `@jit_compile` I had 12 minutes.)

**Comment by holl-** [comment]
While I haven't been able to track down what exactly caused the slow-down, I tested it again in the latest version (3.2, currently on `develop`) and it seemed to be fine. If the problem persists for you, feel free to re-open this issue!
