### ISSUE TITLE
[BUG] adjust bound req, for emb field padding

### ISSUE THREAD

**Issue by m13ammed** [tum-pbs/PhiFlow#179]
I suggest adjusting 
[pad_values mehod](https://github.com/tum-pbs/PhiFlow/blob/5b3d1d0a76b9707b01a5b4896444769c831a4bd0/phi/field/_embed.py#L56)

into
`assert bounds is not None or (already_padded and not value.shape.is_non_uniform), f"{type(self)}.pad() requires 'bounds' argument"`
this prevents diffusion step  (and make incompressible) for padded fields
since during diffusion step the bounds are not auto passed (at least when already_padded = True) and the pad method does not need bounds if it is already padded

**Comment by holl-** [comment]
Hi, thanks for pointing that out!
I think we should pass the bounds argument in the diffusion since it is necessary for evaluating the boundary conditions. Do you have a snippet that reproduces the error?
