### ISSUE TITLE
StaggeredGrid Based Fluid Simulation Not Working with fluid.incompressible_rk4

### ISSUE THREAD

**Issue by BaeHenryS** [tum-pbs/PhiFlow#180]
With the latest version of PhiFlow, the tutorial notebook below, and any other code that uses StaggeredGrid does not work with fluid.incompressible_rk4, and it returns an error. Thank you for your help!

https://tum-pbs.github.io/PhiFlow/Fluid_Simulation.html

<img width="2525" alt="Screenshot 2024-10-30 at 5 11 39 PM" src="https://github.com/user-attachments/assets/bf394a7c-b78f-403c-b998-541c86549760">

**Comment by holl-** [comment]
Sorry for the late response.
Right, higher-order simulations should be run on centered grids on newer versions, like [in this demo](https://tum-pbs.github.io/PhiFlow/examples/grids/Higher_order_Kolmogorov.html). This code was contributed by a student. I'll look into whether we can get higher-order staggered grids running again or whether we should change the documentation.
