### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by lrlunin** [tum-pbs/PhiFlow#19]
First of all I want to thank you for this great library. I am trying now to build library with tf_cuda option on Win10. As I have understood from `setup.py` it can be compiled only with `gcc`. Other variable like `cuda_lib` is also unix specifed. I am not good at C++ programming. So I have the following question. Will be it enough to change the compiler from `gcc` (Linux) to  to `cl` (Win10 Visual Studio) with adapting the line arguments? I'd appreciate any advice or tip. I am also ready to make a pull request later for win-build.

**Comment by holl-** [comment]
Unfortunately, it is much more difficult to compile the CUDA code on Windows than Linux. There is a lot of linking involved to make it compile against the TensorFlow API and I have never done it myself. I would recommend compiling it under Linux if at all possible.

However, even without compiling the CUDA code, you can still make use of the GPU using the default PhiFlow Python implementation, only it's not as fast.

If you manage to get it to compile properly, though, I would be interested in your experience with it.
