### ISSUE TITLE
3d demos

### ISSUE THREAD

**Issue by bmahlbrand** [tum-pbs/PhiFlow#37]
I've tried to modify the basic notebook to run in 3d, but I'm having an issue w/tuple indexing - here's my modified notebook, could anyone advise on what the problem might be?

https://colab.research.google.com/drive/1ZapWnE6Y41lTBkg3xKZGmzuGFME4E8jH?usp=sharing

**Comment by holl-** [comment]
Thank you for testing the latest version!
The error is in the line `buoyancy_force = smoke * (0, 0.5) >> velocity` where the scalar `smoke` field is converted to a vector field. In 3D, it needs 3 components, e.g. `smoke * (0, 0, 0.5)`.
I'll make the error message clearer.

In Google Colab, the fixed version seems to freeze but it runs fine on my machine. Can you confirm this?

**Comment by bmahlbrand** [comment]
I originally tried that, and it froze with another message, but let me confirm whether it runs fine locally :D

**Comment by bmahlbrand** [comment]
I updated the grid size to 16 instead, and now the more recent error occurs for me, did I miss something?

https://colab.research.google.com/drive/1ZapWnE6Y41lTBkg3xKZGmzuGFME4E8jH?usp=sharing

**Comment by holl-** [comment]
The physics runs fine but the viewer currently does not support 3D visualizations.
This will be added eventually but for now, you could just use Matplotlib directly, e.g.
```python
import pylab
pylab.imshow(velocity.vector['x'].values.z[0].numpy('y,x'), origin='lower')
```

**Comment by bmahlbrand** [comment]
eh, right! Thanks for pointing that out. Looks like this issue is resolved - appreciate the prompt responses!
