### ISSUE TITLE
raw pytorch tensors

### ISSUE THREAD

**Issue by bmahlbrand** [tum-pbs/PhiFlow#38]
supposing I'm working solely in pytorch, can you advise on the best practice / expected use of PhiFlow in these cases?

`initial_smoke = CenteredGrid(0, extrapolation.BOUNDARY, x=32, y=40, bounds=Box[0:32, 0:40])`

`initial_velocity = StaggeredGrid(math.zeros(batch(inflow_loc=4)), extrapolation.ZERO, x=32, y=40, bounds=Box[0:32, 0:40])`

I guess I'm digging around for initial_smoke.torch_tensor() or something, I played w/`initial_smoke.values()` but that seems a layer up from what I'm expecting... I could of course convert between numpy and pytorch directly by fetching the numpy tensors/arrays, but that would cause undesirable fetching between cpu and gpu...aside from the obvious breaking of autograd.

Then I'm also looking for an equivalent like `torch.from_numpy(some_torch_tensor)` but to construct a trivial grid in order to use PhiFlow.

Essentially I'm trying to mix and match the functionality instead of completely integrating everything as PhiFlow. Will this be awkward w/how things are set up currently? Sorry if this is covered in docs somewhere, some of the examples seem broken for the moment.

**Comment by holl-** [comment]
Yes, that is a common workflow. There are multiple ways to convert between PhiFlow and native (PyTorch etc.) tensors.

To get the PyTorch tensor from a grid, you can use `grid.values.native(order=grid.shape)` which will keep the dimension order.
The equivalent of `from_numpy` is [`tensor`](https://tum-pbs.github.io/PhiFlow/phi/math/#phi.math.tensor) and [`wrap`](https://tum-pbs.github.io/PhiFlow/phi/math/#phi.math.wrap).
You could construct a grid like so:
```python
CenteredGrid(tensor(np.zeros([4, 3]), spatial('x,y')), extrapolation.ZERO)
```

You can also use [`native_call`](https://tum-pbs.github.io/PhiFlow/phi/math/#phi.math.native_call) to call your PyTorch-specific code.

**Comment by bmahlbrand** [comment]
When I go to create a grid from a pytorch tensor

`y0 = CenteredGrid(wrap(y[:,0]), extrapolation.ZERO)`

I get the following error:

`ValueError: <class 'torch.Tensor'> is not supported. Only (Tensor, tuple, list, np.ndarray, native tensors) are allowed.`

**Comment by bmahlbrand** [comment]
Also - I assume these aren't designed for batches in this direct way? i.e. (batches, channels, x, y, z)

**Comment by holl-** [comment]
To make PhiFlow work with PyTorch, you have to import `phi.torch` beforehand. Otherwise it will not recognize PyTorch tensors.

When creating a PhiFlow-tensor, you have to specify the dimension names and types, e.g.
```python
tensor(y[0], spatial('x,y,z'))
tensor(upsample(vel), channel('vector'), spatial('x,y,z'))
```

**Comment by bmahlbrand** [comment]
Sorry for all the follow-up questions, hopefully it's useful user feedback, but I'm having this problem w/advection:

```
v0 = tensor(upsample(vel[:,0]), batch('batch'), channel('vector'), spatial('x,y,z'))
y0 = tensor(y[:,0 ,0], batch('batch'), spatial('x,y,z'))

ad = advect.mac_cormack(y0, v0, dt=1)
```
```
  File "C:\Users\user\miniconda3\envs\lightning\lib\site-packages\phi\physics\advect.py", line 132, in mac_cormack
    v0 = sample(velocity, field.elements)
  File "C:\Users\user\miniconda3\envs\lightning\lib\site-packages\phi\field\_field.py", line 292, in sample
    assert all(dim not in field.shape for dim in geometry.shape.channel)
AttributeError: 'TensorDim' object has no attribute 'shape'
```

**Comment by bmahlbrand** [comment]
Thanks - this definitely helped!

**Comment by bmahlbrand** [comment]
One more followup - something like ad0.values.native doesn't call detach() or anything internally correct? i.e. if I convert back and forth, how can I ensure the autograd graph is intact?

**Comment by holl-** [comment]
Right, tensors are not detached unless you convert them (e.g. `math.convert()` or `tensor.numpy()`) or use [`math.stop_gradient()`](https://tum-pbs.github.io/PhiFlow/phi/math/#phi.math.stop_gradient). So the autograd graph will stay intact.

**Comment by bmahlbrand** [comment]
Could be expected behavior but when I create a staggeredgrid for velocity values, ie with the shape of 64^3 -- the resulting shape is ```(xˢ=(63, 64, 64), yˢ=(64, 63, 64), zˢ=(64, 64, 63), vectorᵛ=3)```, and then when I attempt to get the native tensor via pytorch ```velocity.values.native(order=velocity.shape))``` this fails due to the ordering of the shape changing. If I use a CenteredGrid instead (just to live with the imperfections without staggered grids), I get notimplemented exceptions in advection operations.

**Comment by holl-** [comment]
Hi, unfortunately staggered grids are always a bit tricky to work with. Have a look [here](https://tum-pbs.github.io/PhiFlow/Staggered_Grids.html) for an overview of what values are stored.

The tensor shape you mentioned is correct for constant extrapolations, such as `ZERO`.
Because the number of sample points varies per velocity components, you cannot call `native()` on `grid.values`. Instead, you can call `grid.staggered_tensor().native('x,y,z')` which fills in the missing values to produce a uniform tensor.

If you use PhiFlow's built-in I/O, it isn't a problem, though. See [`write()`](https://tum-pbs.github.io/PhiFlow/phi/field/#phi.field.write) and [`read()`](https://tum-pbs.github.io/PhiFlow/phi/field/#phi.field.read).

**Comment by bmahlbrand** [comment]
I tried staggered_tensor but got the following error: ```ValueError: tuple.index(x): x not in tuple``` where     print(velocity.values.shape) -> ```(xˢ=(63, 64, 64), yˢ=(64, 63, 64), zˢ=(64, 64, 63), vectorᵛ=3)``` so it should be there in the tuple, no?

**Comment by holl-** [comment]
Sorry, it should be ```grid.staggered_tensor().native('x,y,z,vector')``` (the order of all dimensions need to be specified).

**Comment by bmahlbrand** [comment]
Aha, that fixed it! So I have a follow up question with staggered_grid, it's outputting a 65^3 grid (I assume the extra cell is covering the overlaps once you resample to a uniform grid). I'm curious if it's always going to be dim+1, or if there's something simple I'm overlooking. I can always resample again to 64^3 but wondering if there's a better way to make sure I can export my densities and velocities from sims at the same resolution.

**Comment by holl-** [comment]
The number of values stored depends on the extrapolation, see the [picture here](https://tum-pbs.github.io/PhiFlow/Staggered_Grids.html). However, the `staggered_tensor()` is always of size `n+1` per dimension.
If you don't care about the outer values, I recommend slicing them off the `staggered_tensor`.

**Comment by bmahlbrand** [comment]
Ah nice, I think the most important thing for me at least is just everything being aligned correctly - so ```at_centers()``` seems like a good fit for my usecase! Thanks!

**Comment by holl-** [comment]
Great! Thanks for asking about these things, btw! 2.0 will officially be released next week and it's good to know what's still unclear. You can look forward to tutorial videos coming soon.

**Comment by bmahlbrand** [comment]
Sure! Thanks for the help in getting around the things that weren't immediately obvious :)

great work!

**Comment by holl-** [comment]
No problem! Btw, the first two tutorial videos (math and grids) are live! [Links here](https://tum-pbs.github.io/PhiFlow/). More videos to follow soon-ish. Feel free to keep posting issues!

**Comment by bmahlbrand** [comment]
Nice! Will do!

**Comment by bmahlbrand** [comment]
Sorry to follow up, but I hadn't tried creating a grid from torch since upgrading, and I'm getting this error ```AssertionError: Rank of given shape (vectorᶜ=None, xˢ=None, yˢ=None, zˢ=None) does not match data with sizes (1, 3, 128, 128, 128)``` when I call ```        vel_highres = CenteredGrid(tensor(vel_torch, channel('vector'), spatial('x,y,z')), extrapolation.ZERO)```

**Comment by holl-** [comment]
Looks like vel_torch also contains a batch dimension of size `1` which you could get rid of using `torch.squeeze`

**Comment by holl-** [comment]
Alternatively, you could use `math.reshaped_tensor(vel_torch, [batch(), channel('vector'), *spatial('x, y, z')])`

**Comment by bmahlbrand** [comment]
Ah right, keep forgetting about that detail...thanks >_>
