### ISSUE TITLE
trivial demo example on GPU

### ISSUE THREAD

**Issue by bmahlbrand** [tum-pbs/PhiFlow#40]
Curious if you have a minimal example ala https://github.com/tum-pbs/PhiFlow/blob/master/demos/smoke_plume.py that would demonstrate pushing the simulation onto the GPU backend selected. For example I'm importing phiflow like ```from phi.torch.flow import *```, but not sure what the 'phiflow' way of making sure they're using cuda tensors under the hood. Should I just access the native tensors and overwrite them w/CUDA versions (by moving them in pytorch myself)?

**Comment by holl-** [comment]
Hi, the easiest way to use the GPU with PyTorch is putting this line at the top of your script:
```python
TORCH.set_default_device(TORCH.list_devices('GPU')[0])
```
All tensors created afterwards will be allocated on the GPU.

**Comment by bmahlbrand** [comment]
Nice! Thanks!
