### ISSUE TITLE
random initialized velocity fields

### ISSUE THREAD

**Issue by bmahlbrand** [tum-pbs/PhiFlow#41]
I see ways to initialize velocity fields with a single shape, but can I generate several simultaneously? I'm looking to replicate some of TempoGAN's dataset with randomly initialized velocities.

**Comment by holl-** [comment]
I'm not exactly sure what the question is, but the following is an easy way to generate random velocity fields:
```python
from phi.flow import *
CenteredGrid(Noise(vector=2), extrapolation.ZERO, x=32, y=48)
```

**Comment by bmahlbrand** [comment]
I think you got to the crux of what I was looking for, totally unclear in retrospect :)

**Comment by holl-** [comment]
Maybe I should add that to sample a batch of velocity fields, you can add a batch dimension like this:
```python
Noise(batch(batch=10), vector=2)
```

**Comment by bmahlbrand** [comment]
What about seeding the Noise? Maybe I'm looking to generate random inflows of velocity - can you show a simple example of one? Adding randomized ones together is trivial enough, but not sure if there's some shortcuts to deal w/velocity inflows. Like can I create noise spheres to act as emitters on the velocity field?

**Comment by holl-** [comment]
At the moment, there is no explicit seed control in the `Noise` class, but you can set the global seed using [`math.seed()`](https://tum-pbs.github.io/PhiFlow/phi/math/#phi.math.seed).

As for the spherical inflow, how about something like this:
```python
velocity = StaggeredGrid(0, extrapolation.PERIODIC, x=100, y=80)
inflow = (Noise() @ velocity) * (Sphere((50, 40), radius=10) @ velocity)
velocity += inflow * dt
```

**Comment by holl-** [comment]
Yes, it works in 3D. Try
```python
velocity = StaggeredGrid(0, extrapolation.PERIODIC, x=100, y=80, z=10)
VEL_INFLOW = (Noise(vector=3, scale = 10) @ velocity) * (Sphere((50, 40, 4), radius=10) @ velocity)
```

**Comment by bmahlbrand** [comment]
Ahhh! I upgraded to 2.0.0 ;) that helped.

Also did you change operators? Is ```>>``` valid anymore? Upgraded and now it's complaining about it. I just changed it to ```@``` and it seems to work.

**Comment by holl-** [comment]
Yes, it was renamed to `@` to match `at()`.

**Comment by bmahlbrand** [comment]
Makes sense to me! Thanks.
