### ISSUE TITLE
How to set different dx values for different dimensions in math.spatial_gradient()

### ISSUE THREAD

**Issue by Xunius** [tum-pbs/PhiFlow#61]
Hi,

Currently, the doc says that the `dx` argument of the `math.spatial_gradient()` function is a float. However, reading into the source code, it seems that it is possible to specify different increments for different dimensions, when the `dims` argument contains more than 1 dimensions.

Could the doc be updated, possibly with an example to make this clearer?

**Comment by holl-** [comment]
Fixed: a5b8b7f0542659f329fbb66f5b58398b27f95aa3
