### ISSUE TITLE
a problem about Vis.plot()

### ISSUE THREAD

**Issue by binbinlan** [tum-pbs/PhiFlow#63]
I am very interested in your great work. I follow your work well in coolab but I have a problem when I use 'vis.plot(gird)' in  pycharm  in my local computer,It crashed and said'_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"',how can I sovle it ?

**Comment by holl-** [comment]
This is a problem with your Matplotlib installation. You can try using Plotly: `vis.plot(grid, lib='plotly')
