### ISSUE TITLE
vis.plot() plots with incorrect circle radius

### ISSUE THREAD

**Issue by robert-30** [tum-pbs/PhiFlow#64]
Hi, when I plot a circle with radius 1
```py
import phi.geom as geom
import phi.vis as vis

vis.plot(geom.Sphere(math.tensor([[0, 0]], math.instance(points=None), math.channel(vector='x,y')), math.tensor([1], math.instance(points=None))))
```
The result is a circle with radius \sqrt{2}/2:
![radius_sqrt2_2](https://user-images.githubusercontent.com/16484115/169824873-1c598061-9752-440f-9298-c1d8b7cd339a.png)
It seems that this is caused by the fact that [the radius is converted to the diameter by multiplication with sqrt(2)](https://github.com/tum-pbs/PhiFlow/blob/master/phi/vis/_matplotlib/_matplotlib_plots.py#L277), instead of by multiplication with 2. Replacing 1.41 with 2.0 gives a circle of the expected size: 
![radius_1](https://user-images.githubusercontent.com/16484115/169825865-3001c16f-2e42-4132-ac7b-df5f7da375d5.png)

**Comment by holl-** [comment]
Are you using Plotly for the plots? Unfortunately, the effective size must be specified in pixels and does not scale with the axes. If you zoom in, the sizes will change. I havn't found a good way to fix that.

**Comment by holl-** [comment]
Interesting, when I run the same snippet, I get the correct radius. Maybe they changed how the pixel size behaves across versions? I'm using matplotlib 3.5.2.

**Comment by holl-** [comment]
The matplotlib version doesn't seem to affect the result but running inside a notebook gives different results from opening a window for the figure. Displaying the result inside PyCharm gives different results yet again. Maybe the DPI is affecting it or the figure size somehow changes across displays...

**Comment by holl-** [comment]
Spheres and boxes now plot correctly in any environment using Matplotlib. fa6066ede34cdbb5036c5b0522d45300308ba257
