### ISSUE TITLE
Installation error: Command errored out with exit status 1: python setup.py egg_info

### ISSUE THREAD

**Issue by deruhat** [tum-pbs/PhiFlow#7]
Hello,
Thank you for the amazing work. 
I am trying to install the toolkit using pip as instructed, but I get the following error:

`ERROR: Command errored out with exit status 1:
     command: /home/abushah/anaconda3/envs/cfdnet/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bmlg0_n6/phiflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bmlg0_n6/phiflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bmlg0_n6/phiflow/pip-egg-info
         cwd: /tmp/pip-install-bmlg0_n6/phiflow/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bmlg0_n6/phiflow/setup.py", line 117, in <module>
        with open("documentation/Package_Info.md", "r") as readme:
    FileNotFoundError: [Errno 2] No such file or directory: 'documentation/Package_Info.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Any advice on how to resolve this?

**Comment by holl-** [comment]
There seems to be something wrong with the distribution package. I'll look into it.

**Comment by holl-** [comment]
I uploaded a new distribution that should fix the issue.
