### ISSUE TITLE
`.upsample2x` transposes 2d fields spatially

### ISSUE THREAD

**Issue by danmackinlay** [tum-pbs/PhiFlow#72]
If we generate a random field and upsample we see that the resulting fields are transposed (if you can't see it, look at the two darker blue dots)

![Screen Shot 2022-07-22 at 15 23 53](https://user-images.githubusercontent.com/21740/180368750-28b99c85-27ed-46da-bf31-f0e51dd09ece.png)

MRE

```python
from phi.flow import *
from phi import math, field

math.seed(59)

p = CenteredGrid(
    Noise(
        batch(batch=1),
        scale=0.1,
        smoothness=3),
    x=64,
    y=64,
    bounds=Box(
        x=1.0,
        y=1.0
    )
)

half_p = field.downsample2x(p)
double_p = field.upsample2x(p)
vis.plot([
        p,
        half_p,
        field.upsample2x(half_p),
        double_p,
        field.downsample2x(double_p)
    ],
    show_color_bar=False)
```

**Comment by holl-** [comment]
The upsample function changed the dimension order in a previous version. Upgrading to the latest version should fix it.
```bash
pip uninstall phiflow
pip install --upgrade --quiet git+https://github.com/tum-pbs/PhiFlow@2.2-develop
```

**Comment by holl-** [comment]
I added the fix to `develop` as well, so it will be part of 2.1.4, to be released soon.
