### ISSUE TITLE
Question about Lagrangian Fluid Simulation

### ISSUE THREAD

**Issue by arjun-mani** [tum-pbs/PhiFlow#77]
Hi all,

Thanks for creating this great framework, the differentiability opens up so many possibilities! I am currently working on some control tasks where Lagrangian fluid simulation makes more sense. I know PhiFlow is a Eulerian fluid simulation, but I was wondering whether it can be somehow used for doing Lagrangian simulation. (I'm a bit new to fluid mechanics so I'm not 100% sure if this makes sense as something to do). I would really appreciate your insight. Given your familiarity with the field, I would either way appreciate any ideas on whether differentiable Lagrangian fluid simulation is possible. Or any other frameworks you know of (I know there is some work on learned simulators, but differentiable physics is naturally more robust.) Thanks very much!

Sincerely,
Arjun

**Comment by holl-** [comment]
Have a look at the [FLIP demo](https://github.com/tum-pbs/PhiFlow/blob/master/demos/flip_liquid.py) which uses particles.
There is currently no efficient way to handle neighbor search for particles but we are working on it. If you don't need more than say 20k particles, you can compute the full distance matrix. See the [solar system demo](https://tum-pbs.github.io/PhiFlow/Planets_Tutorial.html) for simple particle-particle interactions.

**Comment by holl-** [comment]
I'm closing the issue for now. If you have further questions, feel free to open it again.
