### ISSUE TITLE
Learning to Control PDEs with Differentiable Physics Source Code?

### ISSUE THREAD

**Issue by deruhat** [tum-pbs/PhiFlow#8]
Hello authors,

I took a look at your recent ICLR2020 paper and it is very intriguing, great work!
I am wondering if the source code for the ICLR2020 paper is included in this repo? If not, are you going to release it soon?

Thank you!

**Comment by holl-** [comment]
Hi!

PhiFlow makes up the largest part of the code used in the paper. It is intended to be used as a library and will show up in future submissions as well.

For this reason, the scripts reproducing the experiments are not included in this codebase. We are currently revising and updating the scripts and will be making them available before ICLR 2020.

The code will be uploaded to [our homepage](https://ge.in.tum.de/publications/2020-iclr-holl/).

**Comment by holl-** [comment]
The experiments code is now available [here](https://github.com/holl-/PDE-Control).
