### ISSUE TITLE
removed matplotlib function in vis animate code

### ISSUE THREAD

**Issue by ParticularlyPythonicBS** [tum-pbs/PhiFlow#85]
vis animate code uses figboxes on[ line 75](https://github.com/tum-pbs/PhiFlow/blob/49cf9c5369dca911748902fd7e1fd26c5dc9df1b/phi/vis/_matplotlib/_matplotlib_plots.py#L75).
This was deprecated in matplotlib 3.4 and has been completely removed since.

So this running this function as shown in many tutorials will raise `AttributeError: 'AxesSubplot' object has no attribute 'figbox'` error to the end user.

To return the original functionality the line will need to be altering following [this issue ](https://github.com/matplotlib/matplotlib/issues/19938) on the matplotlib repo.

**Comment by holl-** [comment]
Thanks! I've pushed a [fix](https://github.com/tum-pbs/PhiFlow/commit/66f7dc07ec757063a8bfb7381036b97bcedc3ef2) to `develop`. The unit tests now pass so I think it should work.
