### ISSUE TITLE
Use of deprecated numpy.object

### ISSUE THREAD

**Issue by ParticularlyPythonicBS** [tum-pbs/PhiFlow#98]
Several parts of the math package use `np.object` , which is deprecated in the latest version of numpy.
This results in an attribute error whenever the phiflow package is imported.
`AttributeError: module 'numpy' has no attribute 'object'` 

The error can be fixed by changing `np.object` usages to `np.object_` as per [numpy documentation](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.object_)

**Comment by holl-** [comment]
This is now fixed in `develop`. You can install it from source or with `pip install --upgrade git+https://github.com/tum-pbs/PhiFlow@develop`
